# Generated by Django 4.1 on 2022-08-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_users_id_alter_users_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
    ]
